image: maven:3.8.5-openjdk-17

stages:
  - build
  - test
  - quality

build:
  stage: build
  script: 
    - ./mvnw package

test:
  stage: test
  script: 
    - ./mvnw test

quality:
  stage: quality
  script: 
    - ./mvnw site